### ISSUE TITLE
Android build failure

### ISSUE THREAD

**Issue by amandeep-wynk** [londonappbrewery/dicee-flutter#9]
Following is the message printed

> Launching lib/main.dart on AOSP on IA Emulator in debug mode...
> [!] Your app isn't using AndroidX.
>     To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
> Running Gradle task 'assembleDebug'...
> 
> FAILURE: Build failed with an exception.

**Comment by TheMuellenator** [comment]
Updated the stub. Should work now.
